#USE A WHITE/LIGHT BLUE BACKGROUND
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(26, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(2, GPIO.OUT)
GPIO.setup(3, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)
import time
from colorama import Fore
GPIO.output(27, GPIO.LOW)
GPIO.output(16, GPIO.LOW)
GPIO.output(26, GPIO.LOW)
GPIO.output(6, GPIO.LOW)
print(f"{Fore.RED}                    -----------------------------")
print(f"{Fore.BLACK}                    |1.Turn on the {Fore.RED}red {Fore.BLACK}light?   |")
print(f"{Fore.BLACK}                    |2.Turn on the {Fore.GREEN}green {Fore.BLACK}light? |")
print(f"{Fore.BLACK}                    |3 Turn on the {Fore.YELLOW}yellow {Fore.BLACK}light?|")
print(f"{Fore.BLACK}                    |4.Turn on the {Fore.BLUE}blue {Fore.BLACK}light?  |")
print(f"{Fore.RED}                    -----------------------------")
time.sleep(5)
print(f"{Fore.BLUE}                     ______________________________________________")
print(f"{Fore.BLUE}                    |                                              |") 
print(f"{Fore.BLUE}                    |{Fore.RED} Answer with the color would like to turn on.{Fore.BLUE} |")
print(f"{Fore.BLUE}                    |                                              |")
print(f"{Fore.BLUE}                    ------------------------------------------------")
color = input("                    >>>")
print(f"{Fore.RED}LOADING...")
print(".")
time.sleep(.2)
print("..")
time.sleep(.2)
print("...")
time.sleep(.2)
print("..")
time.sleep(.2)
print(".")
time.sleep(.2)
print(".")
time.sleep(.2)
print("..")
time.sleep(.2)
print("...")
time.sleep(.2)
print("..")
time.sleep(.2)
print(".")
time.sleep(.2)
print(".")
time.sleep(.2)
print("..")
time.sleep(.2)
print("...")
time.sleep(.2)
print("..")
time.sleep(.2)
print(".")
time.sleep(.2)
print(f"{Fore.RED}DONE!")

#print(f"{Fore.BLACK} ______________________________________________")
#print(f"{Fore.BLACK}|                                              |") 
#print(f"{Fore.BLACK}|{Fore.BLUE} How long would you like it to be on for?{Fore.BLACK}     |")
#print(f"{Fore.BLACK}|                                              |")
#print(f"{Fore.BLACK}------------------------------------------------")
#f = input(">>>")

if color == "red":
    GPIO.output(27, GPIO.HIGH)
if color == "blue":
    GPIO.output(6, GPIO.HIGH)
if color == "yellow":
    GPIO.output(16, GPIO.HIGH)
if color == "green":
    GPIO.output(26, GPIO.HIGH) 